const DbPreLoadUsers = [
	{
		firstName: "John",
		lastName: "Doe",
		username: "johndoe123",
		password: "Qw12345^",
		email: "john.doe@example.com",
		availability: "Anytime Day or Night Any Day",
		phoneNumber: "555-555-5555",
		payPerHour: 25,
		isWorker: true,
		skillLevel: "Basic",
	},
	{
		firstName: "Jane",
		lastName: "Smith",
		username: "janesmith456",
		password: "Qw12345^",
		email: "jane.smith@example.com",
		phoneNumber: "555-555-5556",
		availability: "Only Night shifts Any Day",
		payPerHour: 30,
		isWorker: true,
		skillLevel: "Advanced",
	},
	{
		firstName: "Michael",
		lastName: "Johnson",
		username: "mikej123",
		password: "Qw12345^",
		email: "michael.j@example.com",
		phoneNumber: "555-555-5557",
		availability: "Anytime Day or Night Any Day",
		payPerHour: 22,
		isWorker: true,
		skillLevel: "Basic",
	},
	{
		firstName: "Sarah",
		lastName: "Davis",
		username: "sarahdavis789",
		password: "Qw12345^",
		email: "sarah.davis@example.com",
		phoneNumber: "555-555-5558",
		availability: "Only Night shifts Any Day",
		payPerHour: 35,
		isWorker: true,
		skillLevel: "Advanced",
	},
	{
		firstName: "David",
		lastName: "Brown",
		username: "davidb789",
		password: "Qw12345^",
		email: "david.b@example.com",
		phoneNumber: "555-555-5559",
		availability: "Anytime Day or Night Any Day",
		payPerHour: 40,
		isWorker: true,
		skillLevel: "Basic",
	},
	{
		firstName: "Emily",
		lastName: "Martinez",
		username: "emilym123",
		password: "Qw12345^",
		email: "emily.m@example.com",
		phoneNumber: "555-555-5560",
		availability: "Only Day shifts Any Day",
		payPerHour: 28,
		isWorker: true,
		skillLevel: "Advanced",
	},
	{
		firstName: "James",
		lastName: "Wilson",
		username: "jamesw456",
		password: "Qw12345^",
		email: "james.w@example.com",
		phoneNumber: "555-555-5561",
		availability: "Anytime Day or Night Any Day",
		payPerHour: 38,
		isWorker: true,
		skillLevel: "Basic",
	},
	{
		firstName: "Olivia",
		lastName: "Taylor",
		username: "oliviat789",
		password: "Qw12345^",
		email: "olivia.t@example.com",
		phoneNumber: "555-555-5562",
		availability: "Anytime Day or Night Any Day",
		payPerHour: 32,
		isWorker: true,
		skillLevel: "Pro",
	},
	{
		firstName: "Ethan",
		lastName: "Anderson",
		username: "ethana123",
		password: "Qw12345^",
		email: "ethan.a@example.com",
		phoneNumber: "555-555-5563",
		availability: "Only Day shifts Any Day",
		payPerHour: 26,
		isWorker: true,
		skillLevel: "Pro",
	},
	{
		firstName: "Ava",
		lastName: "Thomas",
		username: "avat456",
		password: "Qw12345^",
		email: "ava.t@example.com",
		phoneNumber: "555-555-5564",
		availability: "Only Day shifts Any Day",
		payPerHour: 34,
		isWorker: true,
		skillLevel: "Advanced",
	},
	{
		firstName: "ABC Oil Co.",
		username: "abcoilco",
		password: "Qw12345^",
		email: "info@abcoilco.com",
		phoneNumber: "555-555-5500",
		businessDescription: "Leading provider of oilfield services.",
		isWorker: false,
	},
	{
		firstName: "XYZ Drilling",
		username: "xyzdrilling",
		password: "Qw12345^",
		email: "info@xyzdrilling.com",
		phoneNumber: "555-555-5501",
		businessDescription: "Specializing in offshore drilling operations.",
		isWorker: false,
	},
	{
		firstName: "Smith Energy Solutions",
		username: "smithenergy",
		password: "Qw12345^",
		email: "info@smithenergy.com",
		phoneNumber: "555-555-5502",
		businessDescription: "Supplying energy solutions for over 50 years.",
		isWorker: false,
	},
	{
		firstName: "Johnson Oilfield Services",
		username: "johnsonoil",
		password: "Qw12345^",
		email: "info@johnsonoil.com",
		phoneNumber: "555-555-5503",
		businessDescription: "Providing top-notch drilling equipment.",
		isWorker: false,
	},
	{
		firstName: "Acme Energy",
		username: "acmeenergy",
		password: "Qw12345^",
		email: "info@acmeenergy.com",
		phoneNumber: "555-555-5504",
		businessDescription: "Delivering innovative energy solutions.",
		isWorker: false,
	},
	{
		firstName: "Pioneer Drilling",
		username: "pioneerdrill",
		password: "Qw12345^",
		email: "info@pioneerdrilling.com",
		phoneNumber: "555-555-5505",
		businessDescription: "Pioneering the way in drilling technology.",
		isWorker: false,
	},
	{
		firstName: "Green Energy Group",
		username: "greenenergy",
		password: "Qw12345^",
		email: "info@greenenergygroup.com",
		phoneNumber: "555-555-5506",
		businessDescription: "Committed to sustainable energy practices.",
		isWorker: false,
	},
	{
		firstName: "Sunburst Energy",
		username: "sunburstenergy",
		password: "Qw12345^",
		email: "info@sunburstenergy.com",
		phoneNumber: "555-555-5507",
		businessDescription: "Harnessing the power of the sun for energy.",
		isWorker: false,
	},
	{
		firstName: "Coastal Oil & Gas",
		username: "coastaloil",
		password: "Qw12345^",
		email: "info@coastaloil.com",
		phoneNumber: "555-555-5508",
		businessDescription: "Leading in offshore drilling operations.",
		isWorker: false,
	},
	{
		firstName: "Thunderbolt Energy",
		username: "thunderbolt",
		password: "Qw12345^",
		email: "info@thunderboltenergy.com",
		phoneNumber: "555-555-5509",
		businessDescription:
			"Energizing the future with cutting-edge technology.",
		isWorker: false,
	},
];

export default DbPreLoadUsers;
